
export const GET_DATA='GET_DATA';
export const GET_DATA_SUCCESS='GET_DATA_SUCCESS';
export const GET_DATA_FAILURE='GET_DATA_FAILURE';

export const ADD_DATA='ADD_DATA';
export const ADD_DATA_SUCCESS='ADD_DATA_SUCCESS';
export const ADD_DATA_FAILURE='ADD_DATA_FAILURE';

export const REMOVE_DATA='REMOVE_DATA';
export const REMOVE_DATA_SUCCESS='REMOVE_DATA_SUCCESS';
export const REMOVE_DATA_FAILURE='REMOVE_DATA_FAILURE';

