export const INCREMENT ='INCREMENT';
export const DECREMENT='DECREMENT';
export const MULTI ='MULTI';
export const DEVIDE='DEVIDE';
export const FETCHING_DATA='FETCHING_DATA';
export const FETCHING_DATA_SUCCESS='FETCHING_DATA_SUCCESS';
export const FETCHING_DATA_FAILURE='FETCHING_DATA_FAILURE';
export const ADD_PERSON='ADD_PERSON';


